--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

--S2:
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO

begin tran
insert dbo.liczby2 values ( 1 )
WAITFOR DELAY '00:00:10'
--S2:
update dbo.liczby1 set liczba=10

--COMMIT

ROLLBACK